/**
 * Vite Plugin: Auto-generate Sprite Collections
 * 
 * Watches public/sprites/ directory and automatically regenerates
 * spriteCollections.generated.ts when SVG files are added/removed.
 * 
 * This enables truly automatic sprite collection discovery - just add
 * a folder with SVGs and they appear immediately in the UI.
 */

import type { Plugin } from 'vite';
import { readdir, stat } from 'node:fs/promises';
import { join, extname, basename } from 'node:path';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface Collection {
  collectionId: string;
  sprites: Array<{ id: string; name: string; svgPath: string }>;
}

/**
 * Sanitize filename to display name
 */
function sanitizeSpriteName(filename: string): string {
  const name = filename.replace(/\.svg$/i, '');
  const withSpaces = name.replace(/[-_]/g, ' ');
  return withSpaces
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
}

/**
 * Generate sprite ID from filename
 */
function generateSpriteId(filename: string): string {
  return basename(filename, '.svg').toLowerCase().replace(/\s+/g, '-');
}

/**
 * Capitalize collection name for display
 */
function capitalizeCollectionName(collectionId: string): string {
  return collectionId
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Check if a path is a directory
 */
async function isDirectory(path: string): Promise<boolean> {
  try {
    const stats = await stat(path);
    return stats.isDirectory();
  } catch {
    return false;
  }
}

/**
 * Generate collections from sprites directory
 */
async function generateCollections(
  spritesDir: string,
  outputFile: string
): Promise<void> {
  try {
    if (!(await isDirectory(spritesDir))) {
      writeEmptyCollections(outputFile);
      return;
    }

    const items = await readdir(spritesDir);
    const collections: Collection[] = [];

    for (const item of items) {
      const itemPath = join(spritesDir, item);
      
      if (!(await isDirectory(itemPath))) {
        continue;
      }

      // Skip "primitives" folder
      if (item === 'primitives') {
        continue;
      }

      // Skip "default" folder - it's handled separately in spriteCollections.ts
      if (item === 'default') {
        continue;
      }

      const files = await readdir(itemPath);
      const svgFiles = files.filter(file => 
        extname(file).toLowerCase() === '.svg'
      );

      if (svgFiles.length === 0) {
        continue;
      }

      const sprites = svgFiles.map(file => {
        const spriteId = generateSpriteId(file);
        const spriteName = sanitizeSpriteName(file);
        const svgPath = `/sprites/${item}/${file}`;

        return {
          id: spriteId,
          name: spriteName,
          svgPath: svgPath,
        };
      });

      sprites.sort((a, b) => a.name.localeCompare(b.name));

      collections.push({
        collectionId: item,
        sprites: sprites,
      });
    }

    generateTypeScriptFile(collections, outputFile);
  } catch (error) {
    console.error('Error generating sprite collections:', error);
  }
}

/**
 * Generate TypeScript file with collections
 */
function generateTypeScriptFile(collections: Collection[], outputFile: string): void {
  const collectionsCode = collections.map(collection => {
    const spritesCode = collection.sprites.map(sprite => {
      return `      { id: "${sprite.id}", name: "${sprite.name}", svgPath: "${sprite.svgPath}" }`;
    }).join(',\n');

    return `  {
    collectionId: "${collection.collectionId}",
    sprites: [
${spritesCode}
    ]
  }`;
  }).join(',\n');

  const fileContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated by vite-plugin-sprite-collections.ts
 * It is regenerated automatically when files in public/sprites/ change.
 * 
 * Last generated: ${new Date().toISOString()}
 */

/**
 * Auto-generated SVG collection definitions
 * Generated from public/sprites/ directory structure
 */
export const autoGeneratedCollections: Array<{
  collectionId: string;
  sprites: Array<{ id: string; name: string; svgPath: string }>;
}> = [
${collectionsCode}
];
`;

  writeFileSync(outputFile, fileContent, 'utf-8');
}

/**
 * Write empty collections file
 */
function writeEmptyCollections(outputFile: string): void {
  const fileContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated by vite-plugin-sprite-collections.ts
 * It is regenerated automatically when files in public/sprites/ change.
 * 
 * Last generated: ${new Date().toISOString()}
 */

/**
 * Auto-generated SVG collection definitions
 * Generated from public/sprites/ directory structure
 */
export const autoGeneratedCollections: Array<{
  collectionId: string;
  sprites: Array<{ id: string; name: string; svgPath: string }>;
}> = [];
`;

  writeFileSync(outputFile, fileContent, 'utf-8');
}

export default function spriteCollectionsPlugin(): Plugin {
  const projectRoot = join(__dirname, '..');
  const spritesDir = join(projectRoot, 'public', 'sprites');
  const outputFile = join(projectRoot, 'src', 'constants', 'spriteCollections.generated.ts');
  // Normalize path for Vite's module resolution
  const outputFileId = outputFile.replace(/\\/g, '/');
  
  // Generate collections immediately when plugin loads
  // This ensures collections are up-to-date even before server starts
  generateCollections(spritesDir, outputFile).catch(err => {
    console.error('Error generating sprite collections on plugin load:', err);
  });

  return {
    name: 'sprite-collections',
    buildStart() {
      // Generate collections on build start (for production builds)
      generateCollections(spritesDir, outputFile);
    },
    configureServer(server) {
      // Generate collections when dev server starts (ensures fresh on server restart)
      generateCollections(spritesDir, outputFile);

      // Watch sprites directory for changes using Vite's watcher
      // Use recursive watching to catch all subdirectory changes
      try {
        server.watcher.add(spritesDir);
      } catch (err) {
        console.warn('Could not add sprites directory to watcher:', err);
      }
      
      let updateTimeout: NodeJS.Timeout | null = null;
      
      const regenerateAndReload = async () => {
        try {
          // Regenerate collections
          await generateCollections(spritesDir, outputFile);
          
          // Get relative path for module resolution
          const relativeOutputPath = outputFile
            .replace(projectRoot, '')
            .replace(/\\/g, '/')
            .replace(/^\//, '');
          
          // Try to find and invalidate the module
          const moduleId = `/${relativeOutputPath}`;
          const module = server.moduleGraph.getModuleById(moduleId);
          
          if (module) {
            server.moduleGraph.invalidateModule(module);
          }
          
          // Force a full reload to ensure all components update with new collections
          server.ws.send({
            type: 'full-reload',
          });
        } catch (error) {
          console.error('Error regenerating sprite collections:', error);
        }
      };
      
      server.watcher.on('all', async (event, changedPath) => {
        // Normalize path separators
        const normalizedPath = changedPath.replace(/\\/g, '/');
        
        // Only react to changes in the sprites folder (exclude default collection)
        if (!normalizedPath.includes('/sprites/') || normalizedPath.includes('/sprites/default/')) {
          return;
        }

        // Check if it's a relevant change
        const isSvgFile = normalizedPath.endsWith('.svg');
        const isDirectoryChange = event === 'addDir' || event === 'unlinkDir';
        const isFileChange = event === 'add' || event === 'unlink';
        
        if (isSvgFile || isDirectoryChange || (isFileChange && normalizedPath.includes('/sprites/'))) {
          // Debounce rapid changes (multiple files added at once)
          if (updateTimeout) {
            clearTimeout(updateTimeout);
          }
          
          updateTimeout = setTimeout(regenerateAndReload, 500); // 500ms debounce
        }
      });
      
      // Regenerate collections on page requests to ensure they're always fresh
      // This handles the case where files were added while server was running
      server.middlewares.use(async (req, res, next) => {
        // Only regenerate on initial page load requests
        if (req.url === '/' || req.url === '/index.html' || (req.url && !req.url.includes('.'))) {
          // Regenerate in background - don't block the request
          generateCollections(spritesDir, outputFile).catch(() => {
            // Silently fail - collections will be regenerated on next change anyway
          });
        }
        next();
      });
      
    },
  };
}
