/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated by vite-plugin-sprite-collections.ts
 * It is regenerated automatically when files in public/sprites/ change.
 * 
 * Last generated: 2025-12-04T12:02:07.573Z
 */

/**
 * Auto-generated SVG collection definitions
 * Generated from public/sprites/ directory structure
 */
export const autoGeneratedCollections: Array<{
  collectionId: string;
  sprites: Array<{ id: string; name: string; svgPath: string }>;
}> = [
  {
    collectionId: "nature",
    sprites: [
      { id: "flower-01", name: "Flower 01", svgPath: "/sprites/nature/flower-01.svg" },
      { id: "flower-02", name: "Flower 02", svgPath: "/sprites/nature/flower-02.svg" },
      { id: "flower-03", name: "Flower 03", svgPath: "/sprites/nature/flower-03.svg" },
      { id: "flower-04", name: "Flower 04", svgPath: "/sprites/nature/flower-04.svg" },
      { id: "flower-05", name: "Flower 05", svgPath: "/sprites/nature/flower-05.svg" },
      { id: "flower-06", name: "Flower 06", svgPath: "/sprites/nature/flower-06.svg" },
      { id: "flower-07", name: "Flower 07", svgPath: "/sprites/nature/flower-07.svg" },
      { id: "flower-08", name: "Flower 08", svgPath: "/sprites/nature/flower-08.svg" },
      { id: "flower-09", name: "Flower 09", svgPath: "/sprites/nature/flower-09.svg" },
      { id: "flower-10", name: "Flower 10", svgPath: "/sprites/nature/flower-10.svg" },
      { id: "frond-01", name: "Frond 01", svgPath: "/sprites/nature/frond-01.svg" },
      { id: "frond-02", name: "Frond 02", svgPath: "/sprites/nature/frond-02.svg" },
      { id: "frond-03", name: "Frond 03", svgPath: "/sprites/nature/frond-03.svg" },
      { id: "frond-04", name: "Frond 04", svgPath: "/sprites/nature/frond-04.svg" },
      { id: "frond-05", name: "Frond 05", svgPath: "/sprites/nature/frond-05.svg" },
      { id: "frond-06", name: "Frond 06", svgPath: "/sprites/nature/frond-06.svg" },
      { id: "frond-07", name: "Frond 07", svgPath: "/sprites/nature/frond-07.svg" },
      { id: "frond-08", name: "Frond 08", svgPath: "/sprites/nature/frond-08.svg" },
      { id: "frond-09", name: "Frond 09", svgPath: "/sprites/nature/frond-09.svg" },
      { id: "frond-10", name: "Frond 10", svgPath: "/sprites/nature/frond-10.svg" },
      { id: "frond-11", name: "Frond 11", svgPath: "/sprites/nature/frond-11.svg" }
    ]
  },
  {
    collectionId: "snowflakes",
    sprites: [
      { id: "snowflake-01", name: "Snowflake 01", svgPath: "/sprites/snowflakes/snowflake-01.svg" },
      { id: "snowflake-02", name: "Snowflake 02", svgPath: "/sprites/snowflakes/snowflake-02.svg" },
      { id: "snowflake-03", name: "Snowflake 03", svgPath: "/sprites/snowflakes/snowflake-03.svg" },
      { id: "snowflake-04", name: "Snowflake 04", svgPath: "/sprites/snowflakes/snowflake-04.svg" },
      { id: "snowflake-05", name: "Snowflake 05", svgPath: "/sprites/snowflakes/snowflake-05.svg" },
      { id: "snowflake-06", name: "Snowflake 06", svgPath: "/sprites/snowflakes/snowflake-06.svg" },
      { id: "snowflake-07", name: "Snowflake 07", svgPath: "/sprites/snowflakes/snowflake-07.svg" },
      { id: "snowflake-08", name: "Snowflake 08", svgPath: "/sprites/snowflakes/snowflake-08.svg" },
      { id: "snowflake-09", name: "Snowflake 09", svgPath: "/sprites/snowflakes/snowflake-09.svg" },
      { id: "snowflake-10", name: "Snowflake 10", svgPath: "/sprites/snowflakes/snowflake-10.svg" },
      { id: "snowflake-11", name: "Snowflake 11", svgPath: "/sprites/snowflakes/snowflake-11.svg" },
      { id: "snowflake-12", name: "Snowflake 12", svgPath: "/sprites/snowflakes/snowflake-12.svg" },
      { id: "snowflake-13", name: "Snowflake 13", svgPath: "/sprites/snowflakes/snowflake-13.svg" },
      { id: "snowflake-14", name: "Snowflake 14", svgPath: "/sprites/snowflakes/snowflake-14.svg" },
      { id: "snowflake-15", name: "Snowflake 15", svgPath: "/sprites/snowflakes/snowflake-15.svg" },
      { id: "snowflake-16", name: "Snowflake 16", svgPath: "/sprites/snowflakes/snowflake-16.svg" }
    ]
  }
];
