/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated by scripts/generate-sprite-collections.js
 * Run "npm run generate:collections" to regenerate this file.
 * 
 * Last generated: 2025-11-28T09:13:53.247Z
 */

/**
 * Auto-generated SVG collection definitions
 * Generated from public/sprites/ directory structure
 */
export const autoGeneratedCollections: Array<{
  collectionId: string;
  sprites: Array<{ id: string; name: string; svgPath: string }>;
}> = [
  {
    collectionId: "christmas",
    sprites: [
      { id: "bauble", name: "Bauble", svgPath: "/sprites/christmas/bauble.svg" },
      { id: "gift", name: "Gift", svgPath: "/sprites/christmas/gift.svg" },
      { id: "holly", name: "Holly", svgPath: "/sprites/christmas/holly.svg" },
      { id: "snowflake", name: "Snowflake", svgPath: "/sprites/christmas/snowflake.svg" },
      { id: "tree", name: "Tree", svgPath: "/sprites/christmas/tree.svg" }
    ]
  }
];
