/**
 * Sprite Collection System
 * 
 * File-based collection discovery for sprite collections.
 * Collections are organized as: public/sprites/{collection-name}/*.svg
 * The "default" collection uses existing shape-based rendering.
 * 
 * SVG collections are automatically discovered from the file system.
 * Run "npm run generate:collections" to regenerate collections after adding new SVG files.
 */

import type { SpriteMode } from "../types/generator";
import { SPRITE_MODES } from "./sprites";
import { autoGeneratedCollections } from "./spriteCollections.generated";

export interface SpriteInfo {
  id: string;
  name: string; // Display name (sanitized from filename)
  svgPath?: string; // Path to SVG file (only for SVG-based sprites)
  spriteMode?: SpriteMode; // For default collection
}

export interface SpriteCollection {
  id: string;
  label: string; // Display name (capitalized collection name)
  isShapeBased: boolean; // true for default, false for SVG collections
  sprites: SpriteInfo[];
}

// SVG collections are automatically generated from public/sprites/ directory
// The generate-sprite-collections.js script scans the directory and creates
// collection definitions. No manual editing needed!
const manualSvgCollections: Array<{
  collectionId: string;
  sprites: Array<{ id: string; name: string; svgPath: string }>;
}> = autoGeneratedCollections;

/**
 * Sanitize filename to display name
 * Converts "christmas-tree.svg" -> "Christmas Tree"
 */
function sanitizeSpriteName(filename: string): string {
  // Remove extension
  const name = filename.replace(/\.svg$/i, '');
  // Replace hyphens/underscores with spaces
  const withSpaces = name.replace(/[-_]/g, ' ');
  // Capitalize words
  return withSpaces
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
}

/**
 * Extract collection ID from path
 * "/sprites/christmas/snowflake.svg" or "/public/sprites/christmas/snowflake.svg" -> "christmas"
 */
function extractCollectionId(path: string): string {
  const match = path.match(/\/sprites\/([^/]+)\//);
  return match ? match[1] : '';
}

/**
 * Extract sprite ID from path
 * "/sprites/christmas/snowflake.svg" -> "snowflake"
 */
function extractSpriteId(path: string): string {
  const match = path.match(/\/([^/]+)\.svg$/);
  return match ? match[1] : '';
}

/**
 * Build collections from manual definitions
 */
function buildCollectionsFromManual(): Map<string, SpriteCollection> {
  const collections = new Map<string, SpriteCollection>();

  // Process manual SVG collection definitions
  for (const manualCollection of manualSvgCollections) {
    // Capitalize collection name for display
    const label = manualCollection.collectionId
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
    
    const collection: SpriteCollection = {
      id: manualCollection.collectionId,
      label,
      isShapeBased: false,
      sprites: manualCollection.sprites.map(sprite => ({
        id: sprite.id,
        name: sprite.name,
        svgPath: sprite.svgPath,
      })),
    };
    
    collections.set(manualCollection.collectionId, collection);
  }

  return collections;
}

/**
 * Create default collection from existing SPRITE_MODES
 */
function createDefaultCollection(): SpriteCollection {
  return {
    id: 'default',
    label: 'Default',
    isShapeBased: true,
    sprites: SPRITE_MODES.map(mode => ({
      id: mode.value,
      name: mode.label,
      spriteMode: mode.value,
    })),
  };
}

// Build all collections
const allCollectionsMap = buildCollectionsFromManual();
// Always add default collection first
allCollectionsMap.set('default', createDefaultCollection());

/**
 * Get all available collections
 */
export function getAllCollections(): SpriteCollection[] {
  return Array.from(allCollectionsMap.values());
}

/**
 * Get a specific collection by ID
 */
export function getCollection(collectionId: string): SpriteCollection | undefined {
  return allCollectionsMap.get(collectionId);
}

/**
 * Get a specific sprite within a collection
 */
export function getSpriteInCollection(
  collectionId: string,
  spriteId: string
): SpriteInfo | undefined {
  const collection = getCollection(collectionId);
  return collection?.sprites.find(sprite => sprite.id === spriteId);
}

/**
 * Check if a collection is shape-based (default) or SVG-based
 */
export function isShapeBasedCollection(collectionId: string): boolean {
  return collectionId === 'default';
}

